### PR TITLE
Add MunVM to list of toy compilers

### PR DESCRIPTION
**Pull request by s0cks**

### CODE REVIEW

**Comment by aalhour** [comment]
Hi! Can you please reorder your change in the list so that the alphabetical order is maintained?

**Comment by s0cks** [comment]
Sure!

**Comment by s0cks** [comment]
I added Eschelle (a language I have been working on for a while to the list as well, there currently isn't too much code since I have been busy with work to finish the rewrite) as well!

**Comment by aalhour** [comment]
Nice! Can you please move Eschelle to the Educational and Toy Projects section?

**Comment by s0cks** [comment]
Done!

**Comment by s0cks** [comment]
Thanks!

**Pull request merged**
