### PR TITLE
Add Haskell related/associated links

### PR DESCRIPTION
**Pull request by MaxwellBo**
- Sourced references from http://dev.stephendiehl.com/hask/#parsing, http://dev.stephendiehl.com/hask/#languages and https://github.com/Gabriel439/post-rfc/blob/master/sotu.md#compilers
- Converted Hackage (Haskell package repository) links to GitHub links, using Hackage links when there was no GitHub repository available

### CODE REVIEW

**Comment by aalhour** [comment]
Hi there, thanks for the contribution. Links don't have to be on GitHub, but it's awesome that you looked for them.

I hate to be that guy but can you please add a dot (.) at the end of your newly added resources? It's just to make formatting more consistent.

_(I discovered an existing ordering bug while reviewing your changes :D but I will take care of it after merging your final changes!)_

**Comment by MaxwellBo** [comment]
All good! I've added the fullstops and rewritten some of the descriptions to match the grammar of the previous sections.

**Comment by aalhour** [comment]
Hello Maxwell, I see that this PR has conflict with master, can you resolve the conflicts?

**Comment by aalhour** [comment]
Oh, and I just noticed that you added a new section under _Tools and Frameworks_ for Haskell but didn't add a link to the new section in the table of contents, can you take care of that too?

**Comment by MaxwellBo** [comment]
Apologies, should be fixed now.

**Comment by aalhour** [comment]
Looks good, thanks and keep 'em coming! 👍

**Pull request merged**
