### PR TITLE
Merge pull request #1 from aalhour/master

### PR DESCRIPTION
**Pull request by xuanruiqi**
Merge all updates in master repo

### CODE REVIEW

**Comment by aalhour** [comment]
Hi there, thanks a lot for contributing, I am not sure about "Elements of ML Programming" book, since a lot of programming languages are being used to write interpreters and compilers, but it wouldn't make sense to turn the General Overview section to be one about general programming.

Can you please exclude that book from your contribution? The rest of the materials look good to me and are awesome 😉

**Comment by xuanruiqi** [comment]
My rationale was that _Elements of ML Programming_ is a nice introduction to functional programming besides ML - and I thought Kernighan and Ritchie's _The C Programming Language_ was also worth a read. But I'll defer to your decision and remove it. On the other hand, I suggest adding another section for reference books of high utility for compiler engineers somewhere.

**Comment by aalhour** [comment]
What would the rationale behind having that section and how would people find it beneficial? Would it contain books only?

**Comment by xuanruiqi** [comment]
Engineering compilers and interpreters is coding-intense and requires a good grasp of data representations and programming conventions in each language. Meanwhile, there are only a few languages (C/C++, Java, ML/OCaml) frequently used to engineer compilers, so the list would be short. Moreover, these books also serve as good examples of language descriptions - handy for people who want to design their own languages.

**Pull request merged**
