### PR TITLE
Addind ZetaVM to the list of Tools and Frameworks.

### PR DESCRIPTION
**Pull request by Maaarcocr**

### CODE REVIEW

**Comment by aalhour** [comment]
Hey @Maaarcocr, thanks for the contribution. Can you please add a `.` at the end of your newly added line?

Thanks.

**Comment by Maaarcocr** [comment]
@aalhour thanks for spotting that out! I just corrected it :)

**Comment by Maaarcocr** [comment]
Hey @aalhour, any other reason why this has not been merged yet?

**Comment by aalhour** [comment]
Hello @Maaarcocr, sorry for the late reply, I hace been on a long vacation.

**Pull request merged**
